title: NFixes
description: This repository contains a list of common fixes for things that I run into. Most of these are things I need for setting up a Linux distro on my personal machine or getting my usual dev environtments setup. There are also some really niche or specific fixes for things that can be hard to find and I'd rather not go down the Google rabbit hole to find them again.

theme: jekyll-theme-minimal
